version: '3.8'

services:
  icecast:
    image: moul/icecast
    volumes:
      - logs:/var/log/icecast2
      - /etc/localtime:/etc/localtime:ro
    environment:
      - ICECAST_SOURCE_PASSWORD=aaa
      - ICECAST_ADMIN_PASSWORD=bbb
      - ICECAST_PASSWORD=ccc
      - ICECAST_RELAY_PASSWORD=ddd
      - ICECAST_HOSTNAME=noise.example.com
    ports:
      - "8000:8000"

  nginx:
    image: nginx:latest
    depends_on:
      - icecast
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"

volumes:
  logs:

